apps/select_template/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.select_for_single ,  
        name='select_for_single',
       
    ),
    url(
        regex=r'^basketball/(?P<pk>\d+)/$',
        view=views.basketball ,  
        name='basketball',
       
    ),
    url(
        regex=r'^clean/(?P<pk>\d+)/$',
        view=views.clean ,  
        name='clean',
       
    ),
    url(
        regex=r'^plain/(?P<pk>\d+)/$',
        view=views.plain ,  
        name='plain',
       
    ),
    url(
        regex=r'^multi/$',
        view=views.select_multiple_students ,  
        name='multi',
       
    ),
    url(
        regex=r'^multi/business/$',
        view=views.business ,  
        name='business',
       
    ),
    ]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from apps import views as homepage_views
from django.contrib.auth.decorators import login_required
from apps.select_template import views as select_template_views

urlpatterns = [
    url(r'^$', homepage_views.home_page , name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^view/', include('apps.select_template.urls', namespace='select_template')),
    url(r'^tinymce/', include('tinymce.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

apps/templates/pages/about.html
{% extends "base.html" %}

apps/templates/pages/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-3">
{% crispy form %}
    
</div>
<div class="col-md-9">
{% if students %}
    <form method="POST" action="{% url 'home' %}" id="multi-select">
         {% csrf_token %}
     <div class="table-responsive">
                 
                    <table class="table table-responsive" id="id_table" data-toggle="table" >
                    <thead>
                    <tr>
                        <th data-field="state" >Check</th>
                     <!--   <th>Student ID</th> -->
                         <th>Name</th>
                    <!--      <th>Pathway</th> -->
                        <th>Major</th>
                        <th>GPA</th>
                      <th>Link</th> 
                       
                    </tr>
                    </thead>
                    <tbody>
                    
                        {% for student in students %}
                        <tr>
                            <td><input type="checkbox" id="check-{{student.pk}}" value="{{student.pk}}" name="choices" /></td> 
                            <td>{{ student.user.username }}</td>
                            <td>{{student.major }}</td>
                            <td>{{student.gpa }}</td>
                            <td><a id="view-{{student.pk }}" href="{% url 'select_template:select_for_single' pk=student.pk  %}">View</a></td>
                         
                        </tr>
                        {% endfor %}
                    
                    </tbody>
                    </table>
                    <input type="submit" id="multi-submit" name="multi-submit" class="btn btn-outline btn-primary btn-lg btn-block medTopMargin" value="Select" />
      </div>    
    </form>
    {% elif form.errors %}
        <div class="form-group has-error">
            <div class="help-block">{{ form.text.errors }}</div>
            <div class="help-block">{{ form.non_field_errors }}  </div>
            
        </div>
    {% endif %}
</div>
{% endblock content %}